import type { HelpContent } from '@/src/components/HelpModal'

export const helpContent: Record<string, HelpContent> = {
  dashboard: {
    title: 'Your Projects',
    whatThisIs: 'This is your home base. All your projects live here. Each project is a campaign with its own strategy, content plan, and library.',
    whatToDo: [
      'Click + New Project to start a new campaign',
      'Click any project to open it and work on its strategy',
      'Use the archive icon to hide projects you are done with',
      'Check the Active Project card for a quick shortcut to your latest project',
    ],
    important: [
      'New projects start on the Strategy page — complete your strategy first',
      'Archived projects can be restored anytime from the Archived view',
    ],
    whatHappensNext: 'Open a project to define your strategy, run an AI audit, and generate your content plan.',
  },

  strategy: {
    title: 'Strategy',
    whatThisIs: 'Your strategy defines who you are targeting, how you want to sound, and what your content should achieve. Everything the AI generates is guided by this.',
    whatToDo: [
      'Complete the strategy interview to fill in your inputs',
      'Add your song lyrics and style in the interview',
      'Run the Strategy Audit to get AI recommendations',
      'Apply any recommendations you agree with',
      'Approve your strategy when you are satisfied',
    ],
    important: [
      'Strategy must be approved before you can generate a Content Plan',
      'Editing your strategy after approval will reset your audit status',
    ],
    whatHappensNext: 'Once approved, go to Content Plan to generate your 30-day plan based on this strategy.',
  },

  plan: {
    title: 'Content Plan',
    whatThisIs: 'Your 30-day content plan is a day-by-day schedule of content ideas generated by AI based on your approved strategy.',
    whatToDo: [
      'Click Generate Plan to create your 30-day content calendar',
      'Browse days and filter by platform',
      'Select a day to view its details',
      'Click Generate Content to create the hook, script, caption, and visuals for any day',
    ],
    important: [
      'You must approve your strategy before generating a plan',
      'Regenerating a plan will replace the current one (library content is kept)',
    ],
    whatHappensNext: 'Generated content for each day is saved to your Library where you can edit, finalize, and post.',
  },

  assets: {
    title: 'Assets',
    whatThisIs: 'Your creative inputs for this project. For music projects, this includes your song lyrics and song style which are used by AI when generating strategy and content.',
    whatToDo: [
      'Paste your full song lyrics',
      'Describe your song style (genre, mood, energy)',
      'Save your changes',
    ],
    important: [
      'Lyrics and Song Style are required to run the Strategy Audit',
      'Changes here improve the quality of all AI-generated content',
    ],
    whatHappensNext: 'After saving your assets, go to Strategy to complete and audit your strategy.',
  },

  chat: {
    title: 'AI Chat',
    whatThisIs: 'A strategy-aware AI assistant that knows your project, strategy, and insights. Use it to brainstorm ideas, refine your approach, or get specific content suggestions.',
    whatToDo: [
      'Ask for hook ideas, content angles, or tone suggestions',
      'Request recommendations to improve your strategy',
      'Brainstorm campaign ideas or promotional angles',
      'Ask about your audience or content approach',
    ],
    whatHappensNext: 'Use the ideas and recommendations from chat to refine your strategy or inspire your content.',
  },

  library: {
    title: 'Library',
    whatThisIs: 'All generated content lives here. You can review, edit, and manage content through its lifecycle: Draft, Ready, and Posted.',
    whatToDo: [
      'Review generated content for each day',
      'Edit hook, script, caption, hashtags, or visuals',
      'Mark content as Ready when finalized',
      'Mark as Posted after publishing',
      'Duplicate content to create variations',
    ],
    whatHappensNext: 'Use the Copy button to grab content for each platform and post it to your social channels.',
  },
}
